# proxy redirect for Helm chart repo
[[redirects]]
   from = "/charts/*"
   to = "https://calico-public.s3.amazonaws.com/charts/:splat"
   status = 200
   headers = {X-From = "Netlify"}

# proxy redirects for website and manifests for v3.25
#[[redirects]]
#  from = "/archive/v3.25/*"
#  to = "https://calico-v3-25.netlify.app/archive/v3.25/:splat"
#  status = 200

# proxy redirects for website and manifests for v3.24
[[redirects]]
  from = "/archive/v3.24/*"
  to = "https://calico-v3-24.netlify.app/archive/v3.24/:splat"
  status = 200

# proxy redirects for website and manifests for v3.23
[[redirects]]
  from = "/archive/v3.23/*"
  to = "https://calico-v3-23.netlify.app/archive/v3.23/:splat"
  force = true
  status = 200

# proxy redirects for website and manifests for v3.22
[[redirects]]
  from = "/archive/v3.22/*"
  to = "https://calico-v3-22.netlify.app/archive/v3.22/:splat"
  status = 200

# proxy redirects for website and manifests for v3.21
[[redirects]]
  from = "/archive/v3.21/*"
  to = "https://calico-v3-21.netlify.app/archive/v3.21/:splat"
  status = 200

# proxy redirects for website and manifests for v3.20
[[redirects]]
  from = "/archive/v3.20/*"
  to = "https://calico-v3-20.netlify.app/archive/v3.20/:splat"
  status = 200

# proxy redirects for website and manifests for v3.19
[[redirects]]
  from = "/archive/v3.19/*"
  to = "https://calico-v3-19.netlify.app/archive/v3.19/:splat"
  status = 200

[[redirects]]
  from = "/v3.19/*"
  to = "https://calico-v3-19.netlify.app/v3.19/:splat"
  status = 200

# proxy redirects for website and manifests for v3.18
[[redirects]]
  from = "/archive/v3.18/*"
  to = "https://calico-v3-18.netlify.app/archive/v3.18/:splat"
  status = 200

[[redirects]]
  from = "/v3.18/*"
  to = "https://calico-v3-18.netlify.app/v3.18/:splat"
  status = 200

# proxy redirects for website and manifests for v3.17
[[redirects]]
  from = "/archive/v3.17/*"
  to = "https://calico-v3-17.netlify.app/archive/v3.17/:splat"
  status = 200

[[redirects]]
  from = "/v3.17/*"
  to = "https://calico-v3-17.netlify.app/v3.17/:splat"
  status = 200

# proxy redirects for website and manifests for v3.16
[[redirects]]
  from = "/archive/v3.16/*"
  to = "https://calico-v3-16.netlify.app/archive/v3.16/:splat"
  status = 200

[[redirects]]
  from = "/v3.16/*"
  to = "https://calico-v3-16.netlify.app/v3.16/:splat"
  status = 200

# proxy redirects for website and manifests for v3.15
[[redirects]]
  from = "/archive/v3.15/*"
  to = "https://calico-v3-15.netlify.app/archive/v3.15/:splat"
  status = 200

[[redirects]]
  from = "/v3.15/*"
  to = "https://calico-v3-15.netlify.app/v3.15/:splat"
  status = 200

# proxy redirects for website and manifests for v3.14
[[redirects]]
  from = "/archive/v3.14/*"
  to = "https://calico-v3-14.netlify.app/archive/v3.14/:splat"
  status = 200

[[redirects]]
  from = "/v3.14/*"
  to = "https://calico-v3-14.netlify.app/v3.14/:splat"
  status = 200

# proxy redirects for website and manifests for v3.13
[[redirects]]
  from = "/archive/v3.13/*"
  to = "https://calico-v3-13.netlify.app/archive/v3.13/:splat"
  status = 200

[[redirects]]
  from = "/v3.13/*"
  to = "https://calico-v3-13.netlify.app/v3.13/:splat"
  status = 200

# proxy redirects for website and manifests for v3.12
[[redirects]]
  from = "/archive/v3.12/*"
  to = "https://calico-v3-12.netlify.app/archive/v3.12/:splat"
  status = 200

[[redirects]]
  from = "/v3.12/*"
  to = "https://calico-v3-12.netlify.app/v3.12/:splat"
  status = 200

# proxy redirects for website for master, it doesn't need manifests redirect
[[redirects]]
  from = "/master/*"
  to = "https://calico-master.netlify.app/master/:splat"
  status = 200

# site redirects for archive sites, one redirect is sufficient for the entire release legacy site.
[[redirects]]
  from = "/archive/*"
  to = "https://calico-legacy.netlify.app/archive/:splat"
  status = 200

# supporting /<version>/manifests/<manifest.yaml> format for archive sites
# all the redirect rules are nessesarry since the proxy needs to know where to redirect for each path
[[redirects]]
  from = "/v3.11/*"
  to = "https://calico-legacy.netlify.app/v3.11/:splat"
  status = 200

[[redirects]]
  from = "/v3.10/*"
  to = "https://calico-legacy.netlify.app/v3.10/:splat"
  status = 200

[[redirects]]
  from = "/v3.9/*"
  to = "https://calico-legacy.netlify.app/v3.9/:splat"
  status = 200

[[redirects]]
  from = "/v3.8/*"
  to = "https://calico-legacy.netlify.app/v3.8/:splat"
  status = 200

[[redirects]]
  from = "/v3.7/*"
  to = "https://calico-legacy.netlify.app/v3.7/:splat"
  status = 200

[[redirects]]
  from = "/v3.6/*"
  to = "https://calico-legacy.netlify.app/v3.6/:splat"
  status = 200

[[redirects]]
  from = "/v3.5/*"
  to = "https://calico-legacy.netlify.app/v3.5/:splat"
  status = 200

[[redirects]]
  from = "/v3.4/*"
  to = "https://calico-legacy.netlify.app/v3.4/:splat"
  status = 200

[[redirects]]
  from = "/v3.3/*"
  to = "https://calico-legacy.netlify.app/v3.3/:splat"
  status = 200

[[redirects]]
  from = "/v3.2/*"
  to = "https://calico-legacy.netlify.app/v3.2/:splat"
  status = 200

[[redirects]]
  from = "/v3.1/*"
  to = "https://calico-legacy.netlify.app/v3.1/:splat"
  status = 200

[[redirects]]
  from = "/v3.0/*"
  to = "https://calico-legacy.netlify.app/v3.0/:splat"
  status = 200

[[redirects]]
  from = "/v2.6/*"
  to = "https://calico-legacy.netlify.app/v2.6/:splat"
  status = 200

[[redirects]]
  from = "/v2.5/*"
  to = "https://calico-legacy.netlify.app/v2.5/:splat"
  status = 200

[[redirects]]
  from = "/v2.4/*"
  to = "https://calico-legacy.netlify.app/v2.4/:splat"
  status = 200

[[redirects]]
  from = "/v2.3/*"
  to = "https://calico-legacy.netlify.app/v2.3/:splat"
  status = 200

[[redirects]]
  from = "/v2.2/*"
  to = "https://calico-legacy.netlify.app/v2.2/:splat"
  status = 200

[[redirects]]
  from = "/v2.1/*"
  to = "https://calico-legacy.netlify.app/v2.1/:splat"
  status = 200

[[redirects]]
  from = "/v2.0/*"
  to = "https://calico-legacy.netlify.app/v2.0/:splat"
  status = 200

[[redirects]]
  from = "/v1.6/*"
  to = "https://calico-legacy.netlify.app/v1.6/:splat"
  status = 200

[[redirects]]
  from = "/v1.5/*"
  to = "https://calico-legacy.netlify.app/v1.5/:splat"
  status = 200

# shifting generic redirect of /<version> to / from _redirects to toml
[[redirects]]
  from = "/latest/*"
  to = "/:splat"
  status = 301

[[redirects]]
  from = "/*"
  to = "https://docs.tigera.io/calico/:splat"
  force = true
  status = 301

[[headers]]
  for = "/*.yaml"
  [headers.values]
    content-type = "text/yaml"

[[headers]]
  for = "/*.yml"
  [headers.values]
    content-type = "text/yaml"

[[headers]]
  for = "/*.sh"
  [headers.values]
    content-type = "text/x-shellscript"

[[headers]]
  for = "/*.bash"
  [headers.values]
    content-type = "text/x-shellscript"