// NOTE: All directories in the content root MUST be accounted for.
// IF they're not, you'll get build errors that do not appear when you run yarn start.

const sidebars = {
  calicoSidebar: [
    //{type: 'ref', id: 'calico/about/about-calico'},
    {
      type: 'category',
      label: 'About',
      link: {
        type: 'doc',
        id: 'calico/about/index',
      },
      items: [
          'calico/about/about-calico',
          'calico/about/about-k8s-networking',
          'calico/about/about-network-policy',
          'calico/about/about-kubernetes-services',
          'calico/about/about-kubernetes-ingress',
          'calico/about/about-kubernetes-egress',
          'calico/about/about-ebpf',
      ],
    },
    {
      type: 'category',
      label: 'Install Calico',
      link: {
        type: 'doc',
        id: 'calico/getting-started/index',
      },
        items: [
          {
            type: 'category',
            label: 'Kubernetes',
            link: {type: 'doc', id: 'calico/getting-started/kubernetes/index'},
            items: [
              {
                type: 'autogenerated',
                dirName: 'calico/getting-started/kubernetes',
              },
            ],
          },
          {
            type: 'category',
            label: 'OpenStack',
            link: {type: 'doc', id: 'calico/getting-started/openstack/index'},
            items: [
              {
                type: 'autogenerated',
                dirName: 'calico/getting-started/openstack',
              },
            ],
          },
          {
            type: 'category',
            label: 'Non-cluster hosts',
            link: {type: 'doc', id: 'calico/getting-started/bare-metal/index'},
            items: [
              {
                type: 'autogenerated',
                dirName: 'calico/getting-started/bare-metal',
              },
            ],
          },
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      link: {type: 'doc', id: 'calico/networking/index'},
      items: [
          'calico/networking/determine-best-networking',
        {
          type: 'category',
          label: 'Configure networking',
          link: {type: 'doc', id: 'calico/networking/configuring/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/networking/configuring',
            },
          ],
        },
        {
          type: 'category',
          label: 'Customize IP address management',
          link: {type: 'doc', id: 'calico/networking/ipam/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/networking/ipam',
            },
          ],
        },
        {
          type: 'category',
          label: 'Calico networking for OpenStack',
          link: {type: 'doc', id: 'calico/networking/openstack/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/networking/openstack',
            },
          ],
        },
        {
          type: 'category',
          label: 'Calico Enterprise',
          link: {type: 'doc', id: 'calico/networking/calico-enterprise/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/networking/calico-enterprise',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Security',
      link: {type: 'doc', id: 'calico/security/index'},
      items: [
        'calico/security/adopt-zero-trust',
        'calico/security/non-privileged',
        {
          type: 'category',
          label: 'Get started with policy',
          link: {type: 'doc', id: 'calico/security/get-started/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/security/get-started',
            },
          ],
        },
        {
          type: 'category',
          label: 'Policy rules',
          link: {type: 'doc', id: 'calico/security/policy-rules/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/security/policy-rules',
            },
          ],
        },
        {
          type: 'category',
          label: 'Policy for hosts',
          link: {type: 'doc', id: 'calico/security/hosts/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/security/hosts',
            },
          ],
        },
        {
          type: 'category',
          label: 'Policy for services',
          link: {type: 'doc', id: 'calico/security/services/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/security/services',
            },
          ],
        },
        {
          type: 'category',
          label: 'Policy for Istio',
          link: {type: 'doc', id: 'calico/security/istio/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/security/istio',
            },
          ],
        },
        {
          type: 'category',
          label: 'Policy for extreme traffic',
          link: {type: 'doc', id: 'calico/security/extreme-traffic/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/security/extreme-traffic',
            },
          ],
        },
          'calico/security/encrypt-cluster-pod-traffic',
        {
          type: 'category',
          label: 'Secure Calico component communications',
          link: {type: 'doc', id: 'calico/security/comms/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/security/comms',
            },
          ],
        },
        {
          type: 'category',
          label: 'Calico Enterprise',
          link: {type: 'doc', id: 'calico/security/calico-enterprise/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/security/calico-enterprise',
            },
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Operations',
      link: {type: 'doc', id: 'calico/maintenance/index'},
      items: [
        {
          type: 'category',
          label: 'Upgrade',
          link: {type: 'doc', id: 'calico/maintenance/upgrading/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/maintenance/upgrading',
            },
          ],
        },
        {
          type: 'category',
          label: 'calicoctl',
          link: {type: 'doc', id: 'calico/maintenance/calicoctl/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/maintenance/calicoctl',
            },
          ],
        },
        {
          type: 'category',
          label: 'Deploy image options',
          link: {type: 'doc', id: 'calico/maintenance/image-options/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/maintenance/image-options',
            },
          ],
        },
          'calico/maintenance/datastore-migration',
          'calico/maintenance/operator-migration',
          'calico/maintenance/install-apiserver',
        {
          type: 'category',
          label: 'eBPF',
          link: {type: 'doc', id: 'calico/maintenance/ebpf/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/maintenance/ebpf',
            },
          ],
        },
        {
          type: 'category',
          label: 'Monitor',
          link: {type: 'doc', id: 'calico/maintenance/monitor/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/maintenance/monitor',
            },
          ],
        },
          'calico/maintenance/decommissioning-a-node',
        {
          type: 'category',
          label: 'Troubleshoot',
          link: {type: 'doc', id: 'calico/maintenance/troubleshoot/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/maintenance/troubleshoot',
            },
          ],
        },
          'calico/maintenance/certificate-management',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {type: 'doc', id: 'calico/reference/index'},
      items: [
          'calico/reference/api',
          //'calico/reference/installation/api',
          // TODO: 'Installation' category needs to be collapsed into single Operator API page
        {
          type: 'category',
          label: 'Installation',
          link: {type: 'doc', id: 'calico/reference/installation/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/installation',
            },
          ],
        },
        {
          type: 'category',
          label: 'calicoctl',
          link: {type: 'doc', id: 'calico/reference/calicoctl/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/calicoctl',
            },
          ],
        },
        {
          type: 'category',
          label: 'Resource definitions',
          link: {type: 'doc', id: 'calico/reference/resources/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/resources',
            },
          ],
        },
        {
          type: 'category',
          label: 'Configuring etcd RBAC',
          link: {type: 'doc', id: 'calico/reference/etcd-rbac/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/etcd-rbac',
            },
          ],
        },
          'calico/reference/configure-calico-node',
        {
          type: 'category',
          label: 'Felix',
          link: {type: 'doc', id: 'calico/reference/felix/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/felix',
            },
          ],
        },
        {
          type: 'category',
          label: 'Typha',
          link: {type: 'doc', id: 'calico/reference/typha/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/typha',
            },
          ],
        },
          'calico/reference/configure-cni-plugins',
        {
          type: 'category',
          label: 'Calico Kubernetes controllers',
          link: {type: 'doc', id: 'calico/reference/kube-controllers/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/kube-controllers',
            },
          ],
        },

        {
          type: 'category',
          label: 'Configuration on public clouds',
          link: {type: 'doc', id: 'calico/reference/public-cloud/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/public-cloud',
            },
          ],
        },
        {
          type: 'category',
          label: 'Host endpoints',
          link: {type: 'doc', id: 'calico/reference/host-endpoints/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/host-endpoints',
            },
          ],
        },
        {
          type: 'category',
          label: 'Architecture',
          link: {type: 'doc', id: 'calico/reference/architecture/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/architecture',
            },
          ],
        },
        {
          type: 'category',
          label: 'VPP dataplane',
          link: {type: 'doc', id: 'calico/reference/vpp/index'},
          items: [
            {
              type: 'autogenerated',
              dirName: 'calico/reference/vpp',
            },
          ],
        },
          'calico/reference/faq',
          'calico/reference/involved',
      ],
    },
    'calico/release-notes/index'
  ],

  calicoEnterpriseSidebar: [
      'calico-enterprise/about-calico-enterprise',
    {
      type: 'category',
      label: 'Install and upgrade',
      link: {
        type: 'generated-index',
        title: 'Install and upgrade',
        /*description: '', */
        slug: 'calico-enterprise/getting-started',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise/getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      link: {
        type: 'generated-index',
        title: 'Networking',
        /*description: '', */
        slug: 'calico-enterprise/networking',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise/networking',
        },
      ],
    },
    {
      type: 'category',
      label: 'Network policy',
      link: {
        type: 'generated-index',
        title: 'Network policy',
        /*description: '', */
        slug: 'calico-enterprise/security',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise/security',
        },
      ],
    },

    {
      type: 'category',
      label: 'Visibility and troubleshooting',
      link: {
        type: 'generated-index',
        title: 'Visibility and troubleshooting',
        /*description: '', */
        slug: 'calico-enterprise/visibility',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise/visibility',
        },
      ],
    },
    {
      type: 'category',
      label: 'Multi-cluster management',
      link: {
        type: 'generated-index',
        title: 'Multi-cluster management',
        /*description: '', */
        slug: 'calico-enterprise/multicluster',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise/multicluster',
        },
      ],
    },
    {
      type: 'category',
      label: 'Threat defense',
      link: {
        type: 'generated-index',
        title: 'Threat defense',
        /*description: 'Learn about the most important Docusaurus concepts!',*/
        slug: '/calico-enterprise/threat',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise/threat',
        },
      ],
    },
    {
      type: 'category',
      label: 'Compliance and security',
      link: {
        type: 'generated-index',
        title: 'Compliance and security',
        /*description: '', */
        slug: 'calico-enterprise/compliance',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise/compliance',
        },
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      link: {
        type: 'generated-index',
        title: 'Operations',
        /*description: '', */
        slug: 'calico-enterprise/operations',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise/maintenance',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        title: 'Reference',
        /*description: '', */
        slug: 'calico-enterprise/reference',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise/reference',
        },
      ],
    },
    'calico-enterprise/release-notes/index'
  ],

  calicoCloudSidebar: [
      'calico-cloud/index',
    {
      type: 'category',
      label: 'Install and upgrade',
      link: {
        type: 'generated-index',
        title: 'Install and upgrade',
        /*description: '', */
        slug: 'calico-cloud/get-started',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/get-started'
        }
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        title: 'Tutorials',
        /*description: '', */
        slug: 'calico-cloud/get-started/tutorials',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/get-started/tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'Workload access controls',
      link: {
        type: 'generated-index',
        title: 'Workload access controls',
        /*description: '', */
        slug: 'calico-cloud/workload-access',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/workload-access',
        },
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/security',
        },
      ],
    },
    {
      type: 'category',
      label: 'Observability and troubleshooting',
      link: {
        type: 'generated-index',
        title: 'Observability and troubleshooting',
        /*description: '', */
        slug: 'calico-cloud/visibility',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/visibility',
        },
      ],
    },
    {
      type: 'category',
      label: 'Threat',
      link: {
        type: 'generated-index',
        title: 'Threat',
        /*description: '', */
        slug: 'calico-cloud/threat',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/threat',
        },
      ],
    },
    {
      type: 'category',
      label: 'Image assurance',
      link: {
        type: 'generated-index',
        title: 'Image assurance',
        /*description: '', */
        slug: 'calico-cloud/image-assurance',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/image-assurance',
        },
      ],
    },
    {
      type: 'category',
      label: 'Compliance and security',
      link: {
        type: 'generated-index',
        title: 'Compliance and security',
        /*description: '', */
        slug: 'calico-cloud/compliance',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/compliance',
        },
      ],
    },
    {
      type: 'category',
      label: 'Networking',
      link: {
        type: 'generated-index',
        title: 'Networking',
        /*description: '', */
        slug: 'calico-cloud/networking',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/networking',
        },
      ],
    },
    {
      type: 'category',
      label: 'User and cluster management',
      link: {
        type: 'generated-index',
        title: 'User and cluster management',
        /*description: '', */
        slug: 'calico-cloud/operations',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/operations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      link: {
        type: 'generated-index',
        title: 'Reference',
        /*description: '', */
        slug: 'calico-cloud/reference',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/reference',
        },
      ],
    },
    {
      type: 'category',
      label: 'Get help',
      link: {
        type: 'generated-index',
        title: 'Get help',
        /*description: '', */
        slug: 'calico-cloud/get-help',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud/get-help',
        },
      ],
    },
      'calico-cloud/release-notes/index',
  ],
};

module.exports = sidebars;
