// This is the navigation file for Calico Open Source

module.exports= {
    calicoSidebar: [
        {
            type: 'category',
            label: 'Calico',
            collapsed: false,
            link: {
                type: 'generated-index',
            },
            items: [
                {
                    type: 'autogenerated',
                    dirName: '.',
                },
            ],
        },
    ],
};