/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  calicoSidebar: [
    {
      type: 'category',
      label: 'Calico',
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico',
        },
      ],
    },
  ],

  calicoEnterpriseSidebar: [
    {
      type: 'category',
      label: 'Calico Enterprise',
      collapsed: false,
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise',
        },
      ],
    },
  ],

  calicoCloudSidebar: [
    {
      type: 'category',
      label: 'Calico Cloud',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'calico-cloud/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-cloud',
        },
      ],
    },
  ],
};

module.exports = sidebars;
