/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docs: [
    {
      type: 'category',
      label: 'Calico',
      link: {
        type: 'generated-index',
      },
      //collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico', // Generate section automatically based on files
        },
      ],
    },
    {
      type: 'category',
      label: 'Calico Enterprise',
      link: {
        type: 'generated-index',
      },
      //collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'calico-enterprise', // Generate section automatically based on files
        },
      ],
    },
    {
      type: 'category',
      label: 'Calico Cloud',
      link: {
        type: 'generated-index',
      },
      //collapsed: false,
      items: [
        'calico-cloud/index',
        {
          type: 'autogenerated',
          dirName: 'calico-cloud', // Generate section automatically based on files
        },
      ],
    },

  ],
};

module.exports = sidebars;
