# This section installs and configures the Calico Enterprise API server.
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
{%- if include.upgradeFromCalico %}
  # Calico OSS creates an APIServer custom resource with the name "default". Use this same name
  # when upgrading from OSS to Enterprise so that there is only a single APIServer
  # custom resource created. Tigera operator will error out if there are multiple APIServer
  # custom resources with the same name.
  name: default
{%- else %}
  name: tigera-secure
{%- endif %}
