# This section includes base {{site.prodname}} installation configuration.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
{%- if include.isOverlay == "true" %}
  name: overlay
{%- else %}
  name: default
{%- endif %}
spec:
  # Install Calico Enterprise
  variant: TigeraSecureEnterprise

  # List of image pull secrets to use when installing images from a container registry.
  # If specified, secrets must be created in the `tigera-operator` namespace.
  imagePullSecrets:
    - name: tigera-pull-secret

  # Optionally, a custom registry to use for pulling images.
  # registry: <my-registry>
{%- if include.useDefaultRegistry == "true" %}
  registry: UseDefault
  imagePath: UseDefault
  imagePrefix: UseDefault
{%- endif %}
{%- if include.kubernetesProvider %}

  # Enables provider-specific settings required for compatibility.
  kubernetesProvider: {{include.kubernetesProvider}}
{%- endif %}

{%- if include.cniPlugin %}

  # Configure the CNI plugin.
  cni:
    type: {{include.cniPlugin}}
{%- endif %}

---

# This section configures the Tigera web manager.
# Remove this section for a Managed cluster.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.Manager
apiVersion: operator.tigera.io/v1
kind: Manager
metadata:
  name: tigera-secure
spec:
  # Authentication configuration for accessing the Tigera manager.
  # Default is to use token-based authentication.
  auth:
    type: Token

---

# This section installs and configures the Calico Enterprise API server.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
{%- if include.upgradeFromCalico %}
  # Calico OSS creates an APIServer custom resource with the name "default". Use this same name
  # when upgrading from OSS to Enterprise so that there is only a single APIServer
  # custom resource created. Tigera operator will error out if there are multiple APIServer
  # custom resources with the same name.
  name: default
{%- else %}
  name: tigera-secure
{%- endif %}

---

# This section installs and configures Calico Enterprise compliance functionality.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.Compliance
apiVersion: operator.tigera.io/v1
kind: Compliance
metadata:
  name: tigera-secure

---

# This section installs and configures Calico Enterprise intrusion detection functionality.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.IntrusionDetection
apiVersion: operator.tigera.io/v1
kind: IntrusionDetection
metadata:
  name: tigera-secure

---

# This section configures the Elasticsearch cluster used by Calico Enterprise.
# Remove this section for a Managed cluster.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.LogStorage
apiVersion: operator.tigera.io/v1
kind: LogStorage
metadata:
  name: tigera-secure
spec:
  nodes:
    count: 1

---

# This section configures collection of Tigera flow, DNS, and audit logs.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.LogCollector
apiVersion: operator.tigera.io/v1
kind: LogCollector
metadata:
  name: tigera-secure

---

# This section configures Prometheus for Calico Enterprise.
# For more information, see: {{site.url}}/{{page.version}}/reference/installation/api#operator.tigera.io/v1.Monitor
apiVersion: operator.tigera.io/v1
kind: Monitor
metadata:
  name: tigera-secure

---
