---
title: calicoctl captured-packets
description: Command to access capture files generated by a PacketCapture. 
canonical_url: '/reference/calicoctl/captured-packets'
---

This section describes the `calicoctl captured-packets` command.

Read the [calicoctl command line interface user reference]({{ site.baseurl }}/reference/calicoctl/overview)
for a full list of calicoctl commands.

## Displaying the help text for 'calicoctl captured-packets' command

Run `calicoctl captured-packets --help` to display the following help menu for the
command.

```
Usage:
  calicoctl captured-packets ( copy | clean ) <NAME>
                [--config=<CONFIG>] [--namespace=<NS>] [--all-namespaces] [--dest=<DEST>]

Examples:
  # Copies capture files for packet capture from default namespace in the current directory.
  calicoctl captured-packets copy my-capture
  # Delete capture files for packet capture from default namespace still left on the system
  calicoctl captured-packets clean my-capture

Options:
  -n --namespace=<NS>      Namespace of the packet capture.
                           Uses the default namespace if not specified. [default: default]
  -a --all-namespaces      If present, list the requested packet capture(s) across all namespaces.
  -d --dest=<DEST>         If present, uses the directory specified as the destination. [default: .]
  -h --help                Show this screen.
  -c --config=<CONFIG>     Path to the file containing connection configuration in
                           YAML or JSON format.
                           [default: /etc/calico/calicoctl.cfg]

Description:
  Commands for accessing Capture related information.

  See 'calicoctl captured-packets <command> --help' to read about a specific subcommand.

```
{: .no-select-button}

## Configure RBAC for calicoctl

In order to authorize users to copy/clean captures files via `calicoctl captured-packets`, the following cluster role and cluster role binding can be used:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calicoctl-captured-packets
rules:
- apiGroups: ["crd.projectcalico.org"]
  resources: ["felixconfigurations"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calicoctl-captured-packets
subjects:
- kind: User
  name: dave
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: calicoctl-captured-packets
  apiGroup: rbac.authorization.k8s.io
```

## Examples of 'calicoctl captured-packets' command

1. Copy capture files generated by PacketCapture my-capture from namespace default.

   ```bash
   calicoctl captured-packets copy my-capture
   ```

   Results indicate that capture files generated by default/my-capture were successfully copied to the current directory.

   ```
   Copy capture files for default/my-capture to .
   ```
   {: .no-select-button}

1. Copy capture files generated by PacketCapture my-capture from namespace default to /tmp.

   ```bash
   calicoctl captured-packets copy my-capture --destination /tmp
   ```

   Results indicate that capture files generated by default/my-capture were successfully copied to /tmp directory.

   ```
   Copy capture files for default/my-capture to /tmp
   ```
   {: .no-select-button}

1. Copy capture files generated by PacketCapture my-capture from namespace my-namespace.
   ```bash
   calicoctl captured-packets copy my-capture --namespace my-namespace
   ```

   Results indicate that capture files generated by my-namespace/my-capture were successfully copied to the current directory.

   ```
   Copy capture files for my-namespace/my-capture to .
   ```
   {: .no-select-button}

1. Copy capture files generated by PacketCapture my-capture from all namespaces.
   ```bash
   calicoctl captured-packets copy my-capture --all-namespaces
   ```

   Results indicate that capture files generated by my-namespace/my-capture and default/my-capture were successfully copied to the current directory.

   ```
   Copy capture files for my-namespace/my-capture to .
   Copy capture files for default/my-capture to .
   ```
   {: .no-select-button}

1. Clean capture files generated by PacketCapture my-capture from namespace my-namespace.
   ```bash
   calicoctl captured-packets clean my-capture --namespace my-namespace
   ```

   Results indicate that capture files generated by my-namespace/my-capture were successfully deleted.

   ```
   Clean capture files for my-namespace/my-capture
   ```
   {: .no-select-button}

1. Clean capture files generated by PacketCapture my-capture from all namespaces.
   ```bash
   calicoctl captured-packets clean my-capture --all-namespaces
   ```

   Results indicate that capture files generated by my-namespace/my-capture and default/my-capture were successfully cleaned.

   ```
   Clean capture files for my-namespace/my-capture to .
   Clean capture files for default/my-capture to .
   ```
   {: .no-select-button}

### Setting the log level

```
  -l --log-level=<level>  Set the log level (one of panic, fatal, error,
                          warn, info, debug) [default: panic]
```
{: .no-select-button}

   ```bash
   calicoctl -l debug captured-packets copy my-capture
   ```

### Options

```
  -n --namespace=<NS>      Namespace of the packet capture.
                           Uses the default namespace if not specified. [default: default]
  -a --all-namespaces      If present, list the requested packet capture(s) across all namespaces.
  -d --dest=<DEST>         If present, uses the directory specified as the destination. [default: .]
```
{: .no-select-button}

### General options

```
  -h --help                Show this screen.
  -c --config=<CONFIG>     Path to the file containing connection configuration in
                           YAML or JSON format.
                           [default: ` + constants.DefaultConfigPath + `]
```
{: .no-select-button}

## See also

-  [Installing calicoctl]({{ site.baseurl }}/maintenance/clis/calicoctl/install)
-  [Resources]({{ site.baseurl }}/reference/resources/overview) for details on all valid resources, including file format
   and schema
