processor:
  # RE2 regular expressions describing types that should be excluded from the generated documentation.
  ignoreTypes:
    - "List$"
    - "AdditionalLogStoreSpec"
    - "AdditionalLogSourceSpec"
    - "AmazonCloudIntegration"
    - "ApplicationLayer"
    - "AuthType"
    - "MetadataAccessAllowedType"
    - "Authentication"
    - "Auth"
    - "AuthMethod"
    - "Compliance"
    - "Dashboards*"
    - "DeepPacketInspectionDaemonset*"
    - "DexDeployment*"
    - "DPIDaemonset*"
    - "ECKOperator*"
    - "EgressGateway"
    - "EksCloudwatchLogsSpec"
    - "EKSLogForwarder*"
    - "Elasticsearch*"
    - "EmailVerificationType"
    - "ESGateway*"
    - "FluentdDaemon*"
    - "GuardianDeployment*"
    - "GroupSearch"
    - "Index"
    - "Indices"
    - "IntrusionDetection"
    - "Kibana*"
    - "LinseedDeployment*"
    - "LogCollect*"
    - "LogStorage"
    - "ManagementCluster"
    - "Manager"
    - "Monitor*$"
    - "Nodes"
    - "NodeSet"
    - "NodeSetSelectionAttribute"
    - "NonClusterHost*"
    - "PacketCaptureAPI"
    - "PolicyRecommendation*"
    - "Prometheus*"
    - "Retention"
    - "S3StoreSpec"
    - "SplunkStoreSpec"
    - "SyslogStoreSpec"
    - "SyslogLogType"
    - "Tenant*"
    - "TLS.*Route"
    - "UserMatch"
    - "UserSearch"
  # RE2 regular expressions describing type fields that should be excluded from the generated documentation.
  ignoreFields:
    - "TypeMeta$"
  customMarkers:
    - name: "optional"
      target: field

render:
  # Version of Kubernetes to use when generating links to Kubernetes API documentation.
  kubernetesVersion: 1.32
  # Generate better link for known types
  #knownTypes:
  #  - name: SecretObjectReference
  #    package: sigs.k8s.io/gateway-api/apis/v1beta1
  #    link: https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1beta1.SecretObjectReference
