---
title: Attribution
description: Attribution report 
canonical_url: '/reference/attribution/attribution'
---

### {{site.prodname}} attribution report

24 Feb 2021

{{site.prodname}} incorporates various open source softwares. The following open source components and their respective licenses used in the product are provided for your informational purposes.
In the table below, you can look at the details of each project and license associated with it.

<table dir="ltr" border="1" cellspacing="0" cellpadding="0"><colgroup><col width="384" /><col width="376" /><col width="100" /></colgroup>
<tbody>
	<tr>
		<td style="background-color: #696969; color: #fff; font-weight: bold">Project</td>
		<td style="background-color: #696969; color: #fff; font-weight: bold">Artifact Name</td>
		<td style="background-color: #696969; color: #fff; font-weight: bold">LICENSE</td>
	</tr>
	<tr>
		<td>abbrev</td>
		<td>abbrev-1.1.1.tgz</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>algoliasearch</td>
		<td>algoliasearch.umd-4.2.0.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>ansi-regex</td>
		<td>ansi-regex-2.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>ansi-styles</td>
		<td>ansi-styles-3.2.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@types/anymatch</td>
		<td>anymatch-1.3.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>app-policy</td>
		<td>app-policy-v3.16.6</td>
		<td>Tigera Proprietory</td>
	</tr>
	<tr>
		<td>argparse</td>
		<td>argparse-1.0.9.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>arr-diff</td>
		<td>arr-diff-4.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>arr-flatten</td>
		<td>arr-flatten-1.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>arr-union</td>
		<td>arr-union-3.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>array-unique</td>
		<td>array-unique-0.3.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>asap</td>
		<td>asap-2.0.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>assign-symbols</td>
		<td>assign-symbols-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>atob</td>
		<td>atob-2.1.2.tgz</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>atomicwrites</td>
		<td>atomicwrites-1.4.0-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>attrs</td>
		<td>attrs-20.3.0-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>avsdf-base</td>
		<td>avsdf-base-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>babel-standalone</td>
		<td>babel-6.26.0.min.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>babel-runtime</td>
		<td>babel-runtime-6.26.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>backports.functools-lru-cache</td>
		<td>backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>balanced-match</td>
		<td>balanced-match-0.4.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>balanced-match</td>
		<td>balanced-match-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>base</td>
		<td>base-0.11.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>beautifulsoup4</td>
		<td>beautifulsoup4-4.9.3-py2-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>big.js</td>
		<td>big.js-5.2.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>boolbase</td>
		<td>boolbase-1.0.0.tgz</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>twitter-bootstrap</td>
		<td>bootstrap-3.3.7.min.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>bootstrap</td>
		<td>bootstrap-3.4.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>brace-expansion</td>
		<td>brace-expansion-1.1.11.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>braces</td>
		<td>braces-2.3.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>bs4</td>
		<td>bs4-0.0.1.tar.gz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>buffer-from</td>
		<td>buffer-from-1.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cache-base</td>
		<td>cache-base-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cachetools</td>
		<td>cachetools-3.1.1-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>projectcalico</td>
		<td>calico-v3.17.1</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>projectcalico</td>
		<td>calicoctl-v3.17.1</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>camel-case</td>
		<td>camel-case-4.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>certifi</td>
		<td>certifi-2020.12.5-py2.py3-none-any.whl</td>
		<td>Mozilla 2.0</td>
	</tr>
	<tr>
		<td>chain-function</td>
		<td>chain-function-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>chalk</td>
		<td>chalk-2.4.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>chardet</td>
		<td>chardet-3.0.4-py2.py3-none-any.whl</td>
		<td>LGPL 3.0</td>
	</tr>
	<tr>
		<td>chardet</td>
		<td>chardet-4.0.0-py2.py3-none-any.whl</td>
		<td>LGPL 3.0</td>
	</tr>
	<tr>
		<td>chevrotain</td>
		<td>chevrotain-6.5.0.tgz</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>cidr-regex</td>
		<td>cidr-regex-2.0.10.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>class-transformer</td>
		<td>class-transformer-0.3.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>class-utils</td>
		<td>class-utils-0.3.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>class-validator</td>
		<td>class-validator-0.9.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>classnames</td>
		<td>classnames-2.2.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>classnames</td>
		<td>classnames-2.2.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>clean-css</td>
		<td>clean-css-4.2.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>clipboard.js</td>
		<td>clipboard-2.0.0.min.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cni-plugin</td>
		<td>cni-plugin-v3.16.6</td>
		<td>Tigera Proprietory</td>
	</tr>
	<tr>
		<td>@babel/code-frame</td>
		<td>code-frame-7.10.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>codemirror</td>
		<td>codemirror-5.57.0.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>codemirror</td>
		<td>codemirror-5.57.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>collection-visit</td>
		<td>collection-visit-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>color-convert</td>
		<td>color-convert-1.9.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>color-name</td>
		<td>color-name-1.1.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>commander</td>
		<td>commander-2.13.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>commander</td>
		<td>commander-2.20.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>commander</td>
		<td>commander-4.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>component-emitter</td>
		<td>component-emitter-1.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>concat-map</td>
		<td>concat-map-0.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>configparser</td>
		<td>configparser-4.0.2-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>connected-react-router</td>
		<td>connected-react-router-6.5.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>contextlib2</td>
		<td>contextlib2-0.6.0.post1-py2.py3-none-any.whl</td>
		<td>Python 2.0</td>
	</tr>
	<tr>
		<td>copy-descriptor</td>
		<td>copy-descriptor-0.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@popperjs/core</td>
		<td>core-2.4.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>core-js</td>
		<td>core-js-1.2.7.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>core-js</td>
		<td>core-js-2.5.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>core-js</td>
		<td>core-js-2.5.7.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>core-js</td>
		<td>core-js-3.6.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cose-base</td>
		<td>cose-base-1.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>create-react-class</td>
		<td>create-react-class-15.6.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>css-box-model</td>
		<td>css-box-model-1.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>css-select</td>
		<td>css-select-1.2.0.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>css-what</td>
		<td>css-what-2.1.3.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>@ungap/custom-elements</td>
		<td>custom-elements-0.1.12.tgz</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>cytoscape</td>
		<td>cytoscape-3.15.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape</td>
		<td>cytoscape-3.18.0.min.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-avsdf</td>
		<td>cytoscape-avsdf-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-cise</td>
		<td>cytoscape-cise-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-context-menus</td>
		<td>cytoscape-context-menus-4.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-cose-bilkent</td>
		<td>cytoscape-cose-bilkent-4.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-dagre-cluster-fix</td>
		<td>cytoscape-dagre-cluster-fix-2.2.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-expand-collapse</td>
		<td>cytoscape-expand-collapse-4.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-fcose</td>
		<td>cytoscape-fcose-1.2.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-layers</td>
		<td>cytoscape-layers-2.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-navigator</td>
		<td>cytoscape-navigator-2.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-popper</td>
		<td>cytoscape-popper-1.0.7.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>cytoscape-popper</td>
		<td>cytoscape-popper-1.0.7.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>d3</td>
		<td>d3-5.5.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-array</td>
		<td>d3-array-1.2.1.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-array</td>
		<td>d3-array-1.2.4.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-axis</td>
		<td>d3-axis-1.0.8.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-brush</td>
		<td>d3-brush-1.0.4.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-chord</td>
		<td>d3-chord-1.0.4.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-collection</td>
		<td>d3-collection-1.0.4.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-collection</td>
		<td>d3-collection-1.0.7.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-color</td>
		<td>d3-color-1.0.3.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-contour</td>
		<td>d3-contour-1.2.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-dispatch</td>
		<td>d3-dispatch-1.0.3.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-drag</td>
		<td>d3-drag-1.2.1.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-dsv</td>
		<td>d3-dsv-1.0.8.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-ease</td>
		<td>d3-ease-1.0.3.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-fetch</td>
		<td>d3-fetch-1.1.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-force</td>
		<td>d3-force-1.1.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-format</td>
		<td>d3-format-1.2.2.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-geo</td>
		<td>d3-geo-1.10.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-hierarchy</td>
		<td>d3-hierarchy-1.1.6.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-interpolate</td>
		<td>d3-interpolate-1.1.6.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-interpolate</td>
		<td>d3-interpolate-1.3.2.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-path</td>
		<td>d3-path-1.0.5.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-polygon</td>
		<td>d3-polygon-1.0.3.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-quadtree</td>
		<td>d3-quadtree-1.0.3.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-random</td>
		<td>d3-random-1.1.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-sankey-circular</td>
		<td>d3-sankey-circular-0.34.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>d3-scale</td>
		<td>d3-scale-2.0.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-scale</td>
		<td>d3-scale-2.1.2.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-scale-chromatic</td>
		<td>d3-scale-chromatic-1.3.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-selection</td>
		<td>d3-selection-1.3.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-shape</td>
		<td>d3-shape-1.2.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-shape</td>
		<td>d3-shape-1.2.3.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-shape</td>
		<td>d3-shape-1.3.7.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-time</td>
		<td>d3-time-1.0.8.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-time-format</td>
		<td>d3-time-format-2.1.1.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-timer</td>
		<td>d3-timer-1.0.7.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-transition</td>
		<td>d3-transition-1.1.1.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-voronoi</td>
		<td>d3-voronoi-1.1.2.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>d3-zoom</td>
		<td>d3-zoom-1.7.1.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>dagre</td>
		<td>dagre-0.7.4.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>dagre-cluster-fix</td>
		<td>dagre-cluster-fix-0.9.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>debug</td>
		<td>debug-2.6.9.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>decimal.js-light</td>
		<td>decimal.js-light-2.5.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>decode-uri-component</td>
		<td>decode-uri-component-0.2.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>deepdiff</td>
		<td>deepdiff-3.3.0-py2-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>deepmerge</td>
		<td>deepmerge-2.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>define-properties</td>
		<td>define-properties-1.1.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>define-properties</td>
		<td>define-properties-1.1.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>define-property</td>
		<td>define-property-0.2.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>define-property</td>
		<td>define-property-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>define-property</td>
		<td>define-property-2.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>diff</td>
		<td>diff-3.5.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>diff2html</td>
		<td>diff2html-2.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>dom-converter</td>
		<td>dom-converter-0.2.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>dom-helpers</td>
		<td>dom-helpers-3.3.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>dom-helpers</td>
		<td>dom-helpers-3.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>dom-serializer</td>
		<td>dom-serializer-0.2.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>dom-walk</td>
		<td>dom-walk-0.1.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>domelementtype</td>
		<td>domelementtype-1.3.1.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>domelementtype</td>
		<td>domelementtype-2.0.1.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>domhandler</td>
		<td>domhandler-2.4.2.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>domutils</td>
		<td>domutils-1.5.1.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>domutils</td>
		<td>domutils-1.7.0.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>dot-case</td>
		<td>dot-case-3.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>elasticsearch</td>
		<td>elasticsearch-6.8.1-py2.py3-none-any.whl</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>elementary-circuits-directed-graph</td>
		<td>elementary-circuits-directed-graph-1.2.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>emojis-list</td>
		<td>emojis-list-3.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>encoding</td>
		<td>encoding-0.1.12.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>entities</td>
		<td>entities-1.1.2.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>entities</td>
		<td>entities-2.0.3.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>es-abstract</td>
		<td>es-abstract-1.17.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>es-to-primitive</td>
		<td>es-to-primitive-1.2.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>es5-shim</td>
		<td>es5-shim-4.3.1.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>escape-string-regexp</td>
		<td>escape-string-regexp-1.0.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>esprima</td>
		<td>esprima-4.0.0.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>expand-brackets</td>
		<td>expand-brackets-2.1.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>extend-shallow</td>
		<td>extend-shallow-2.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>extend-shallow</td>
		<td>extend-shallow-3.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>extglob</td>
		<td>extglob-2.0.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>fast-levenshtein</td>
		<td>fast-levenshtein-2.0.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>fbjs</td>
		<td>fbjs-0.8.16.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>felix</td>
		<td>felix-v3.17.2</td>
		<td>Tigera Proprietory</td>
	</tr>
	<tr>
		<td>file-saver</td>
		<td>file-saver-2.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>fill-range</td>
		<td>fill-range-4.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@fortawesome/fontawesome-common-types</td>
		<td>fontawesome-common-types-0.2.32.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@fortawesome/fontawesome-svg-core</td>
		<td>fontawesome-svg-core-1.2.10.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>for-in</td>
		<td>for-in-1.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>foreach</td>
		<td>foreach-2.0.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>fork-ts-checker-webpack-plugin</td>
		<td>fork-ts-checker-webpack-plugin-4.1.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>formik</td>
		<td>formik-2.1.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>fragment-cache</td>
		<td>fragment-cache-0.2.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@fortawesome/free-brands-svg-icons</td>
		<td>free-brands-svg-icons-5.6.1.tgz</td>
		<td>CC BY 4.0</td>
	</tr>
	<tr>
		<td>@fortawesome/free-regular-svg-icons</td>
		<td>free-regular-svg-icons-5.15.1.tgz</td>
		<td>CC BY 4.0</td>
	</tr>
	<tr>
		<td>@fortawesome/free-solid-svg-icons</td>
		<td>free-solid-svg-icons-5.6.1.tgz</td>
		<td>CC BY 4.0</td>
	</tr>
	<tr>
		<td>funcsigs</td>
		<td>funcsigs-1.0.2-py2.py3-none-any.whl</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>function-bind</td>
		<td>function-bind-1.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>get-value</td>
		<td>get-value-2.0.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/alecthomas/participle</td>
		<td>github.com/alecthomas/participle-v0.3.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/apparentlymart/go-cidr/cidr</td>
		<td>github.com/apparentlymart/go-cidr/cidr-v1.0.1</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/aquasecurity/kube-bench/check</td>
		<td>github.com/aquasecurity/kube-bench/check-v0.0.34</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/araddon/dateparse</td>
		<td>github.com/araddon/dateparse-262228af701ebf3932b8b8488da6781b9d585c88</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/avast/retry-go</td>
		<td>github.com/avast/retry-go-v2.2.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/aws/aws-lambda-go/events</td>
		<td>github.com/aws/aws-lambda-go/events-v1.13.3</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/aws/aws-sdk-go/aws</td>
		<td>github.com/aws/aws-sdk-go/aws-v1.25.8</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/bmizerany/pat</td>
		<td>github.com/bmizerany/pat-6226ea591a40176dd3ff9cd8eff81ed6ca721a00</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/bronze1man/gostrongswanvici</td>
		<td>github.com/bronze1man/gostrongswanvici-27d02f80ba4008de552efb746b3f6eaa7718b518</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/buger/jsonparser</td>
		<td>github.com/buger/jsonparser-v1.0.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/burntsushi/toml</td>
		<td>github.com/burntsushi/toml-v0.3.1</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/caimeo/iniflags</td>
		<td>github.com/caimeo/iniflags-ef4ae6c5cd79d20db0b18bc5ebd8657fac7260e5</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>github.com/cloudflare/cfssl/log</td>
		<td>github.com/cloudflare/cfssl/log-v1.4.1</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>github.com/containernetworking/cni/libcni</td>
		<td>github.com/containernetworking/cni/libcni-v0.8.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/containernetworking/plugins/pkg/hns</td>
		<td>github.com/containernetworking/plugins/pkg/hns-v0.8.5</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/coreos/go-oidc</td>
		<td>github.com/coreos/go-oidc-v2.1.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/coreos/go-semver/semver</td>
		<td>github.com/coreos/go-semver/semver-v0.3.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/davecgh/go-spew/spew</td>
		<td>github.com/davecgh/go-spew/spew-v1.1.1</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>github.com/docker/docker/api/types</td>
		<td>github.com/docker/docker/api/types-v1.13.1</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/docker/docker/client</td>
		<td>github.com/docker/docker/client-v1.13.1</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/docker/go-connections/nat</td>
		<td>github.com/docker/go-connections/nat-v0.4.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/docopt/docopt-go</td>
		<td>github.com/docopt/docopt-go-ee0de3bc6815ee19d4a46c7eb90f829db0e014b1</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/elastic/go-elasticsearch/v7</td>
		<td>github.com/elastic/go-elasticsearch/v7-v7.3.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/envoyproxy/data-plane-api/envoy/api/v2/core</td>
		<td>github.com/envoyproxy/data-plane-api/envoy/api/v2/core-ffd420ef8a9ad148642236aa6d89e2855b41c821</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/fsnotify/fsnotify</td>
		<td>github.com/fsnotify/fsnotify-v1.4.9</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/gavv/monotime</td>
		<td>github.com/gavv/monotime-30dba43534243e3484a34676a0f068d12b989f84</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/getlantern/deepcopy</td>
		<td>github.com/getlantern/deepcopy-v1</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/ghodss/yaml</td>
		<td>github.com/ghodss/yaml-v1.0.0</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/go-ini/ini</td>
		<td>github.com/go-ini/ini-v1.43.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/go-logr/logr</td>
		<td>github.com/go-logr/logr-v0.3.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/go-openapi/spec</td>
		<td>github.com/go-openapi/spec-v0.19.3</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/go-sql-driver/mysql</td>
		<td>github.com/go-sql-driver/mysql-v1.4.1</td>
		<td>Mozilla 2.0</td>
	</tr>
	<tr>
		<td>github.com/gofrs/flock</td>
		<td>github.com/gofrs/flock-v0.8.0</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/gogo/googleapis/google/rpc</td>
		<td>github.com/gogo/googleapis/google/rpc-v1.2.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/gogo/protobuf/proto</td>
		<td>github.com/gogo/protobuf/proto-v1.3.1</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/golang-collections/collections/stack</td>
		<td>github.com/golang-collections/collections/stack-604e922904d35e97f98a774db7881f049cd8d970</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/google/go-cmp/cmp</td>
		<td>github.com/google/go-cmp/cmp-v0.4.0</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/google/gofuzz</td>
		<td>github.com/google/gofuzz-v1.1.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/google/gopacket</td>
		<td>github.com/google/gopacket-v1.1.18</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/google/netstack/tcpip/header</td>
		<td>github.com/google/netstack/tcpip/header-55fcc16cd0eb096d8418f7bc5162483c31a4e82b</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/hashicorp/go-version</td>
		<td>github.com/hashicorp/go-version-v1.2.1</td>
		<td>Mozilla 2.0</td>
	</tr>
	<tr>
		<td>github.com/hashicorp/golang-lru</td>
		<td>github.com/hashicorp/golang-lru-v0.5.1</td>
		<td>Mozilla 2.0</td>
	</tr>
	<tr>
		<td>github.com/hashicorp/yamux</td>
		<td>github.com/hashicorp/yamux-2f1d1f20f75d5404f53b9edf6b53ed5505508675</td>
		<td>Mozilla 2.0</td>
	</tr>
	<tr>
		<td>github.com/howeyc/fsnotify</td>
		<td>github.com/howeyc/fsnotify-v0.9.0</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/hpcloud/tail</td>
		<td>github.com/hpcloud/tail-v1.0.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/ishidawataru/sctp</td>
		<td>github.com/ishidawataru/sctp-00ab2ac2db07a138417639ef3f39672c65dbb9a0</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/jarcoal/httpmock</td>
		<td>github.com/jarcoal/httpmock-v1.0.5</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/jinzhu/copier</td>
		<td>github.com/jinzhu/copier-v0.1.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/jmespath/go-jmespath</td>
		<td>github.com/jmespath/go-jmespath-0.3.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/joho/godotenv</td>
		<td>github.com/joho/godotenv-v1.3.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/jpillora/backoff</td>
		<td>github.com/jpillora/backoff-v1.0.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/json-iterator/go</td>
		<td>github.com/json-iterator/go-v1.1.10</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/juju/clock</td>
		<td>github.com/juju/clock-9c5c9712527c7986f012361e7d13756b4d99543d</td>
		<td>LGPL 3.0</td>
	</tr>
	<tr>
		<td>github.com/juju/errors</td>
		<td>github.com/juju/errors-3fe23663418fc1d724868c84f21b7519bbac7441</td>
		<td>LGPL 3.0</td>
	</tr>
	<tr>
		<td>github.com/juju/mutex</td>
		<td>github.com/juju/mutex-d21b13acf4bfd8a8b0482a3a78e44d98880b40d3</td>
		<td>LGPL 3.0</td>
	</tr>
	<tr>
		<td>github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils</td>
		<td>github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/utils-v1.1.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/kardianos/osext</td>
		<td>github.com/kardianos/osext-2bc1f35cddc0cc527b4bc3dce8578fc2a6c11384</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/kelseyhightower/envconfig</td>
		<td>github.com/kelseyhightower/envconfig-v1.4.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/kelseyhightower/memkv</td>
		<td>github.com/kelseyhightower/memkv-v0.1.1</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/konsorten/go-windows-terminal-sequences</td>
		<td>github.com/konsorten/go-windows-terminal-sequences-v1.0.1</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/lestrrat-go/file-rotatelogs</td>
		<td>github.com/lestrrat-go/file-rotatelogs-v2.4.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/libp2p/go-reuseport</td>
		<td>github.com/libp2p/go-reuseport-v0.0.1</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>github.com/lithammer/dedent</td>
		<td>github.com/lithammer/dedent-v1.1.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/mailru/easyjson</td>
		<td>github.com/mailru/easyjson-v0.7.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/masterminds/sprig</td>
		<td>github.com/masterminds/sprig-v2.19.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/mcuadros/go-version</td>
		<td>github.com/mcuadros/go-version-92cdf37c5b7579ebaf7a036da94b40995972088d</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/microsoft/hcsshim</td>
		<td>github.com/microsoft/hcsshim-v0.8.6</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/mipearson/rfw</td>
		<td>github.com/mipearson/rfw-6f0a6f3266ba1058df9ef0c94cda1cecd2e62852</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/mitchellh/go-homedir</td>
		<td>github.com/mitchellh/go-homedir-v1.1.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/modern-go/concurrent</td>
		<td>github.com/modern-go/concurrent-1.0.3</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/modern-go/reflect2</td>
		<td>github.com/modern-go/reflect2-v1.0.1</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/natefinch/atomic</td>
		<td>github.com/natefinch/atomic-a62ce929ffcc871a51e98c6eba7b20321e3ed62d</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/nmrshll/go-cp</td>
		<td>github.com/nmrshll/go-cp-61436d3b7cfa1bc1e8e455c35d8f60b8e51ccc2e</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/nxadm/tail</td>
		<td>github.com/nxadm/tail-v1.4.4</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/olekukonko/tablewriter</td>
		<td>github.com/olekukonko/tablewriter-v0.0.2</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/olivere/elastic/v7</td>
		<td>github.com/olivere/elastic/v7-v7.0.6</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/onsi/ginkgo</td>
		<td>github.com/onsi/ginkgo-v1.15.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/onsi/gomega</td>
		<td>github.com/onsi/gomega-v1.7.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/openshift/api/config/v1</td>
		<td>github.com/openshift/api/config/v1-d0822898eabb929c40c5146116252477abab8d18</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/openshift/library-go/pkg/crypto</td>
		<td>github.com/openshift/library-go/pkg/crypto-9350cd67a9110bcaf9a85d391fa264afbbff1342</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/osrg/gobgp/client</td>
		<td>github.com/osrg/gobgp/client-v1.22</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/paloaltonetworks/pango</td>
		<td>github.com/paloaltonetworks/pango-v0.1.1</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>github.com/patrickmn/go-cache</td>
		<td>github.com/patrickmn/go-cache-v2.1.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/pkg/errors</td>
		<td>github.com/pkg/errors-v0.8.1</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>github.com/projectcalico/cni-plugin</td>
		<td>github.com/projectcalico/cni-plugin</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/projectcalico/felix</td>
		<td>github.com/projectcalico/felix</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/projectcalico/go-json</td>
		<td>github.com/projectcalico/go-json/json-6219dc7339ba20ee4c57df0a8baac62317d19cb1</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>github.com/projectcalico/go-yaml-wrapper</td>
		<td>github.com/projectcalico/go-yaml-wrapper-090425220c545f6d179db17af395f5aac30b6926</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>kube-controllers</td>
		<td>kube-controllers</td>
		<td>Tigera Proprietory</td>
	</tr>
	<tr>
		<td>github.com/projectcalico/libcalico-go</td>
		<td>github.com/projectcalico/libcalico-go/lib</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/projectcalico/pod2daemon</td>
		<td>github.com/projectcalico/pod2daemon</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>typha</td>
		<td>typha</td>
		<td>Tigera Proprietory</td>
	</tr>
	<tr>
		<td>github.com/prometheus/client_golang/</td>
		<td>github.com/prometheus/client_golang/prometheus-v1.7.1</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/rakelkar/gonetsh/netsh</td>
		<td>github.com/rakelkar/gonetsh/netsh-e5c5ffe4bdf04bc060fc45ff4aca2349f51c94a7</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/robfig/cron</td>
		<td>github.com/robfig/cron-v1.2.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/satori/go.uuid</td>
		<td>github.com/satori/go.uuid-v1.2.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/shirou/gopsutil/process</td>
		<td>github.com/shirou/gopsutil/process-v2.19.03</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/sirupsen/logrus</td>
		<td>github.com/sirupsen/logrus-v1.4.2</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/sirupsen/logrus</td>
		<td>github.com/sirupsen/logrus-v1.6.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/spf13/cobra</td>
		<td>github.com/spf13/cobra-v0.0.3</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/spf13/cobra</td>
		<td>github.com/spf13/cobra-v1.0.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/spf13/pflag</td>
		<td>github.com/spf13/pflag-v1.0.5</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/spf13/viper</td>
		<td>github.com/spf13/viper-v1.6.1</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/stretchr/testify</td>
		<td>github.com/stretchr/testify/mock-v1.4.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/termie/go-shutil</td>
		<td>github.com/termie/go-shutil-bcacb06fecaeec8dc42af03c87c6949f4a05c74c</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/tigera/api</td>
		<td>github.com/tigera/api/</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/vishvananda/netlink</td>
		<td>github.com/vishvananda/netlink-v1.1.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/willf/bitset</td>
		<td>github.com/willf/bitset-v1.1.11</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/workiva/go-datastructures/trie/ctrie</td>
		<td>github.com/workiva/go-datastructures/trie/ctrie-v1.0.50</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>github.com/x-cray/logrus-prefixed-formatter</td>
		<td>github.com/x-cray/logrus-prefixed-formatter-v0.5.2</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/yalp/jsonpath</td>
		<td>github.com/yalp/jsonpath-5cc68e5049a040829faef3a44c00ec4332f6dec7</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>global</td>
		<td>global-4.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>go.etcd.io/etcd/</td>
		<td>go.etcd.io/etcd/client-v0.5.0-alpha.5.0.20201125193152-8a03d2e9614b</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>go.uber.org/zap</td>
		<td>go.uber.org/zap-v1.15.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>golang.org/x/crypto</td>
		<td>golang.org/x/crypto/</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>golang.org/x/net</td>
		<td>golang.org/x/net/</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>golang.org/x/sync/</td>
		<td>golang.org/x/sync/</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>golang.org/x/sys</td>
		<td>golang.org/x/sys</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>github.com/golang/text</td>
		<td>golang.org/x/text</td>
		<td>Golang BSD + Patents</td>
	</tr>
	<tr>
		<td>golang.zx2c4.com/wireguard/</td>
		<td>golang.zx2c4.com/wireguard/</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>google-libphonenumber</td>
		<td>google-libphonenumber-3.2.2.tgz</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>google.golang.org/grpc</td>
		<td>google.golang.org/grpc-v1.27.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>google-auth</td>
		<td>google_auth-1.26.1-py2.py3-none-any.whl</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>gopkg.in/fsnotify/fsnotify.v1</td>
		<td>gopkg.in/fsnotify/fsnotify.v1-v1.4.7</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>gopkg.in/go-playground/validator.v9</td>
		<td>gopkg.in/go-playground/validator.v9-v9.30.2</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>gopkg.in/inf.v0</td>
		<td>gopkg.in/inf.v0-v0.9.0</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>gopkg.in/natefinch/lumberjack.v2</td>
		<td>gopkg.in/natefinch/lumberjack.v2-v2.0.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>gopkg.in/square/go-jose.v2</td>
		<td>gopkg.in/square/go-jose.v2-v2.2.3</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>gopkg.in/tchap/go-patricia.v2/patricia</td>
		<td>gopkg.in/tchap/go-patricia.v2/patricia-v2.3.0</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>gopkg.in/tomb.v1</td>
		<td>gopkg.in/tomb.v1-dd632973f1e7218eb1089048e0798ec9ae7dceb8</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>gopkg.in/yaml.v2</td>
		<td>gopkg.in/yaml.v2-v2.4.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>graphlib</td>
		<td>graphlib-2.1.8.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>gud</td>
		<td>gud-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>has</td>
		<td>has-1.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>has-flag</td>
		<td>has-flag-3.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>has-symbols</td>
		<td>has-symbols-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>has-value</td>
		<td>has-value-0.3.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>has-value</td>
		<td>has-value-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>has-values</td>
		<td>has-values-0.1.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>has-values</td>
		<td>has-values-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>he</td>
		<td>he-1.2.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>heap</td>
		<td>heap-0.2.6.tgz</td>
		<td>Python 2.0</td>
	</tr>
	<tr>
		<td>@babel/helper-validator-identifier</td>
		<td>helper-validator-identifier-7.10.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@babel/highlight</td>
		<td>highlight-7.10.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>history</td>
		<td>history-4.9.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>twitter</td>
		<td>hogan.js</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>hogan.js</td>
		<td>hogan.js-3.0.2.tgz</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>hoist-non-react-statics</td>
		<td>hoist-non-react-statics-3.1.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>hoist-non-react-statics</td>
		<td>hoist-non-react-statics-3.3.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>@types/html-minifier-terser</td>
		<td>html-minifier-terser-5.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>html-minifier-terser</td>
		<td>html-minifier-terser-5.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>html-webpack-plugin</td>
		<td>html-webpack-plugin-4.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>htmlparser2</td>
		<td>htmlparser2-3.10.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>humps</td>
		<td>humps-2.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>icepick</td>
		<td>icepick-1.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>iconv-lite</td>
		<td>iconv-lite-0.4.23.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>idna</td>
		<td>idna-2.10-py2.py3-none-any.whl</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>idna</td>
		<td>idna-2.7-py2.py3-none-any.whl</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>immutable</td>
		<td>immutable-3.8.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>importlib-metadata</td>
		<td>importlib_metadata-2.1.1-py2.py3-none-any.whl</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>inherits</td>
		<td>inherits-2.0.4.tgz</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>instantsearch.js</td>
		<td>instantsearch.production-4.4.1.min.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>invariant</td>
		<td>invariant-2.2.2.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>invariant</td>
		<td>invariant-2.2.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>ip-regex</td>
		<td>ip-regex-2.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>ip-regex</td>
		<td>ip-regex-4.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>ipaddr.js</td>
		<td>ipaddr.js-1.9.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>ipaddress</td>
		<td>ipaddress-1.0.23-py2.py3-none-any.whl</td>
		<td>Python 2.0</td>
	</tr>
	<tr>
		<td>is-accessor-descriptor</td>
		<td>is-accessor-descriptor-0.1.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-accessor-descriptor</td>
		<td>is-accessor-descriptor-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-buffer</td>
		<td>is-buffer-1.1.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-callable</td>
		<td>is-callable-1.1.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-cidr</td>
		<td>is-cidr-3.1.0.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>is-data-descriptor</td>
		<td>is-data-descriptor-0.1.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-data-descriptor</td>
		<td>is-data-descriptor-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-date-object</td>
		<td>is-date-object-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-descriptor</td>
		<td>is-descriptor-0.1.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-descriptor</td>
		<td>is-descriptor-1.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-extendable</td>
		<td>is-extendable-0.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-extendable</td>
		<td>is-extendable-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-ip</td>
		<td>is-ip-3.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-number</td>
		<td>is-number-3.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-plain-object</td>
		<td>is-plain-object-2.0.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-regex</td>
		<td>is-regex-1.0.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-stream</td>
		<td>is-stream-1.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-symbol</td>
		<td>is-symbol-1.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>is-windows</td>
		<td>is-windows-1.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>isarray</td>
		<td>isarray-0.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>isarray</td>
		<td>isarray-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>isobject</td>
		<td>isobject-2.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>isobject</td>
		<td>isobject-3.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>isomorphic-fetch</td>
		<td>isomorphic-fetch-2.2.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>jquery</td>
		<td>jquery-2.2.0.min.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>jquery</td>
		<td>jquery-3.4.0.min.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>js-cookie</td>
		<td>js-cookie-2.2.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>js-tokens</td>
		<td>js-tokens-3.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>js-tokens</td>
		<td>js-tokens-4.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>js-yaml</td>
		<td>js-yaml-3.14.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>jsan</td>
		<td>jsan-3.1.13.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>json5</td>
		<td>json5-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>jsonpickle</td>
		<td>jsonpickle-2.0.0-py2.py3-none-any.whl</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>jsrsasign</td>
		<td>jsrsasign-5.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>k8s.io/api</td>
		<td>k8s.io/api</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/apiextensions-apiserver/</td>
		<td>k8s.io/apiextensions-apiserver/</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/apimachinery</td>
		<td>k8s.io/apimachinery/</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/apiserver</td>
		<td>k8s.io/apiserver</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/client-go</td>
		<td>k8s.io/client-go/</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/component-base/</td>
		<td>k8s.io/component-base/</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/klog</td>
		<td>k8s.io/klog-v1.0.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/kube-aggregator/</td>
		<td>k8s.io/kube-aggregator/</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/kube-openapi/</td>
		<td>k8s.io/kube-openapi</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/kubernetes/</td>
		<td>k8s.io/kubernetes/</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>k8s.io/utils/strings</td>
		<td>k8s.io/utils/strings</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>keycode</td>
		<td>keycode-2.1.9.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>kind-of</td>
		<td>kind-of-3.2.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>kind-of</td>
		<td>kind-of-4.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>kind-of</td>
		<td>kind-of-5.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>kind-of</td>
		<td>kind-of-6.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>kube-controllers</td>
		<td>kube-controllers-v3.0.11</td>
		<td>Tigera Proprietory</td>
	</tr>
	<tr>
		<td>kube-controllers</td>
		<td>kube-controllers-v3.16.6</td>
		<td>Tigera Proprietory</td>
	</tr>
	<tr>
		<td>kubernetes</td>
		<td>kubernetes-12.0.1-py2.py3-none-any.whl</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>layout-base</td>
		<td>layout-base-1.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>projectcalico</td>
		<td>libcalico-go-v3.18.0-0.dev</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>loader-utils</td>
		<td>loader-utils-1.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>lodash</td>
		<td>lodash-4.17.19.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>lodash</td>
		<td>lodash-4.17.20.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>lodash-es</td>
		<td>lodash-es-4.17.15.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>lodash.debounce</td>
		<td>lodash.debounce-4.0.8.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>lodash.get</td>
		<td>lodash.get-4.4.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>lodash.isequal</td>
		<td>lodash.isequal-4.5.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>lodash.throttle</td>
		<td>lodash.throttle-4.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>lodash.topath</td>
		<td>lodash.topath-4.5.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>pimterry</td>
		<td>loglevel-v1.6.8</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>loose-envify</td>
		<td>loose-envify-1.3.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>loose-envify</td>
		<td>loose-envify-1.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>lower-case</td>
		<td>lower-case-2.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>map-cache</td>
		<td>map-cache-0.2.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>map-visit</td>
		<td>map-visit-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>math-expression-evaluator</td>
		<td>math-expression-evaluator-1.2.17.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>megacubo</td>
		<td>megacubo-br-Megacubo_15.4.7_linux_ia32</td>
		<td>LGPL 2.1</td>
	</tr>
	<tr>
		<td>memoize-one</td>
		<td>memoize-one-4.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>microevent.ts</td>
		<td>microevent.ts-0.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>micromatch</td>
		<td>micromatch-3.1.10.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>min-document</td>
		<td>min-document-2.19.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>mini-create-react-context</td>
		<td>mini-create-react-context-0.3.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>minimatch</td>
		<td>minimatch-3.0.4.tgz</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>minimist</td>
		<td>minimist-1.2.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>mixin-deep</td>
		<td>mixin-deep-1.3.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>mkdirp</td>
		<td>mkdirp-0.3.0.tgz</td>
		<td>MIT X11</td>
	</tr>
	<tr>
		<td>mocha</td>
		<td>mocha-1.6.0.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>moment</td>
		<td>moment-2.22.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>more-itertools</td>
		<td>more_itertools-5.0.0-py2-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>ms</td>
		<td>ms-2.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>nanoid</td>
		<td>nanoid-2.1.7.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>nanomatch</td>
		<td>nanomatch-1.2.13.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>netaddr</td>
		<td>netaddr-0.7.19-py2.py3-none-any.whl</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>no-case</td>
		<td>no-case-3.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@types/node</td>
		<td>node-9.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>node-fetch</td>
		<td>node-fetch-1.7.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>nodejs</td>
		<td>node-v10.23.1</td>
		<td>Node.js</td>
	</tr>
	<tr>
		<td>node</td>
		<td>node-v3.17.2</td>
		<td>Tigera Proprietory</td>
	</tr>
	<tr>
		<td>nopt</td>
		<td>nopt-1.0.10.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>nose-timer</td>
		<td>nose-timer-0.7.1.tar.gz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>nose-parameterized</td>
		<td>nose_parameterized-0.6.0-py2.py3-none-any.whl</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>nth-check</td>
		<td>nth-check-1.0.2.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>oauthlib</td>
		<td>oauthlib-3.1.0-py2.py3-none-any.whl</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>object-assign</td>
		<td>object-assign-4.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>object-copy</td>
		<td>object-copy-0.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>object-inspect</td>
		<td>object-inspect-1.7.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>object-keys</td>
		<td>object-keys-1.0.11.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>object-keys</td>
		<td>object-keys-1.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>object-visit</td>
		<td>object-visit-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>object.assign</td>
		<td>object.assign-4.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>object.getownpropertydescriptors</td>
		<td>object.getownpropertydescriptors-2.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>object.pick</td>
		<td>object.pick-1.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>oidc-client</td>
		<td>oidc-client-1.4.1.tgz</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>openshift</td>
		<td>origin-v3.6.1</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>packaging</td>
		<td>packaging-20.9-py2.py3-none-any.whl</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>param-case</td>
		<td>param-case-3.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>parse-duration</td>
		<td>parse-duration-0.4.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>pascal-case</td>
		<td>pascal-case-3.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>pascalcase</td>
		<td>pascalcase-0.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>path-to-regexp</td>
		<td>path-to-regexp-1.7.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>pathlib2</td>
		<td>pathlib2-2.3.5-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>pegjs</td>
		<td>pegjs-0.10.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>performance-now</td>
		<td>performance-now-2.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>pluggy</td>
		<td>pluggy-0.13.1-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>popper.js</td>
		<td>popper-1.16.0.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>popper.js</td>
		<td>popper.js-1.16.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>posix-character-classes</td>
		<td>posix-character-classes-0.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>pretty-error</td>
		<td>pretty-error-2.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>process</td>
		<td>process-0.11.10.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>promise</td>
		<td>promise-7.3.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>prop-types</td>
		<td>prop-types-15.5.10.js</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>prop-types</td>
		<td>prop-types-15.6.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>prop-types</td>
		<td>prop-types-15.6.2.js</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>prop-types</td>
		<td>prop-types-15.6.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>prop-types</td>
		<td>prop-types-15.7.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>prop-types-extra</td>
		<td>prop-types-extra-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>py</td>
		<td>py-1.10.0-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>pyasn1</td>
		<td>pyasn1-0.4.8-py2.py3-none-any.whl</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>pyasn1-modules</td>
		<td>pyasn1_modules-0.2.8-py2.py3-none-any.whl</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>pyparsing</td>
		<td>pyparsing-2.4.7-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>pytest</td>
		<td>pytest-4.6.11-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>python-dateutil</td>
		<td>python_dateutil-2.8.1-py2.py3-none-any.whl</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>PyYAML</td>
		<td>PyYAML-5.4.1-cp27-cp27mu-manylinux1_x86_64.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>raf</td>
		<td>raf-3.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>raf-schd</td>
		<td>raf-schd-4.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>raven-js</td>
		<td>raven-js-3.22.1.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>react</td>
		<td>react-15.6.1.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react</td>
		<td>react-16.13.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react</td>
		<td>react-16.8.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-beautiful-dnd</td>
		<td>react-beautiful-dnd-10.0.2.tgz</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>react-bootstrap</td>
		<td>react-bootstrap-0.32.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-codemirror2</td>
		<td>react-codemirror2-5.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-confirm</td>
		<td>react-confirm-0.1.16.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-cytoscapejs</td>
		<td>react-cytoscapejs-1.2.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>plotly</td>
		<td>react-cytoscapejs-v1.2.1</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-day-picker</td>
		<td>react-day-picker-7.4.8.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-dom</td>
		<td>react-dom-15.6.1.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-dom</td>
		<td>react-dom-16.13.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-dom</td>
		<td>react-dom-16.8.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-draggable</td>
		<td>react-draggable-3.0.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-fast-compare</td>
		<td>react-fast-compare-2.0.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-filter-box</td>
		<td>react-filter-box-3.4.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@fortawesome/react-fontawesome</td>
		<td>react-fontawesome-0.1.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-grid-layout</td>
		<td>react-grid-layout-0.16.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-hot-loader</td>
		<td>react-hot-loader-4.12.21.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-input-autosize</td>
		<td>react-input-autosize-2.1.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>JedWatson</td>
		<td>react-input-autosize-v2.1.2</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-is</td>
		<td>react-is-16.6.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-is</td>
		<td>react-is-16.8.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-is</td>
		<td>react-is-16.9.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-json-pretty</td>
		<td>react-json-pretty-2.2.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-lifecycles-compat</td>
		<td>react-lifecycles-compat-3.0.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-native-segmented-control-tab</td>
		<td>react-native-segmented-control-tab-3.2.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-new-window</td>
		<td>react-new-window-0.1.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-notification-system</td>
		<td>react-notification-system-0.2.17.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-overlays</td>
		<td>react-overlays-0.8.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-prop-types</td>
		<td>react-prop-types-0.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-querybuilder</td>
		<td>react-querybuilder-3.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-redux</td>
		<td>react-redux-5.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-redux</td>
		<td>react-redux-7.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-redux-form</td>
		<td>react-redux-form-1.16.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-resizable</td>
		<td>react-resizable-1.7.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-resize-detector</td>
		<td>react-resize-detector-2.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-router</td>
		<td>react-router-5.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-router-dom</td>
		<td>react-router-dom-5.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-show</td>
		<td>react-show-2.0.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-smooth</td>
		<td>react-smooth-1.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-split-pane</td>
		<td>react-split-pane-0.1.92.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-style-proptype</td>
		<td>react-style-proptype-3.2.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-switch</td>
		<td>react-switch-5.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-table-6</td>
		<td>react-table-6-6.11.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-table</td>
		<td>react-table-7.5.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-tooltip</td>
		<td>react-tooltip-4.2.11.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>react-transition-group</td>
		<td>react-transition-group-2.2.1.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>react-transition-group</td>
		<td>react-transition-group-2.7.1.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>readable-stream</td>
		<td>readable-stream-3.6.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>recharts</td>
		<td>recharts-1.5.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>recharts-scale</td>
		<td>recharts-scale-0.4.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>reduce-css-calc</td>
		<td>reduce-css-calc-1.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>reduce-function-call</td>
		<td>reduce-function-call-1.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>redux</td>
		<td>redux-4.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>redux</td>
		<td>redux-4.0.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>redux-immutable</td>
		<td>redux-immutable-4.0.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>redux-merge-immutable-reducers</td>
		<td>redux-merge-immutable-reducers-0.1.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>redux-thunk</td>
		<td>redux-thunk-2.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>reflect-metadata</td>
		<td>reflect-metadata-0.1.13.tgz</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>regenerator-runtime</td>
		<td>regenerator-runtime-0.11.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>regenerator-runtime</td>
		<td>regenerator-runtime-0.12.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>regenerator-runtime</td>
		<td>regenerator-runtime-0.13.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>regenerator-runtime</td>
		<td>regenerator-runtime-0.13.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>regex-not</td>
		<td>regex-not-1.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>regexp-to-ast</td>
		<td>regexp-to-ast-0.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>relateurl</td>
		<td>relateurl-0.2.7.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>remotedev-serialize</td>
		<td>remotedev-serialize-0.1.8.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>renderkid</td>
		<td>renderkid-2.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>repeat-element</td>
		<td>repeat-element-1.1.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>repeat-string</td>
		<td>repeat-string-1.6.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>requests</td>
		<td>requests-2.20.1-py2.py3-none-any.whl</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>requests</td>
		<td>requests-2.25.1-py2.py3-none-any.whl</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>requests-oauthlib</td>
		<td>requests_oauthlib-1.3.0-py2.py3-none-any.whl</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>reselect</td>
		<td>reselect-2.5.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@juggle/resize-observer</td>
		<td>resize-observer-3.2.0.tgz</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>resize-observer-polyfill</td>
		<td>resize-observer-polyfill-1.5.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>resolve-pathname</td>
		<td>resolve-pathname-2.2.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>resolve-url</td>
		<td>resolve-url-0.2.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>ret</td>
		<td>ret-0.1.15.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>rsa</td>
		<td>rsa-4.5-py2.py3-none-any.whl</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>@babel/runtime</td>
		<td>runtime-7.1.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@babel/runtime</td>
		<td>runtime-7.5.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@babel/runtime-corejs2</td>
		<td>runtime-corejs2-7.1.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>rw</td>
		<td>rw-1.3.3.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>safe-buffer</td>
		<td>safe-buffer-5.2.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>safe-regex</td>
		<td>safe-regex-1.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>safer-buffer</td>
		<td>safer-buffer-2.1.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>scandir</td>
		<td>scandir-1.10.0.tar.gz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>scheduler</td>
		<td>scheduler-0.13.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>scheduler</td>
		<td>scheduler-0.18.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>scheduler</td>
		<td>scheduler-0.19.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>seamless-immutable</td>
		<td>seamless-immutable-7.1.4.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>semver</td>
		<td>semver-5.7.1.tgz</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>set-value</td>
		<td>set-value-2.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>setimmediate</td>
		<td>setimmediate-1.0.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>setuptools</td>
		<td>setuptools-44.1.1-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>shallow-compare</td>
		<td>shallow-compare-1.2.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>shallowequal</td>
		<td>shallowequal-1.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>sigs.k8s.io/controller-runtime</td>
		<td>sigs.k8s.io/controller-runtime-v0.7.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>sigs.k8s.io/kind/pkg/errors</td>
		<td>sigs.k8s.io/kind/pkg/errors-v0.9.0</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>sigs.k8s.io/yaml</td>
		<td>sigs.k8s.io/yaml-v1.2.0</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>simplejson</td>
		<td>simplejson-3.13.2.tar.gz</td>
		<td>Academic 2.1</td>
	</tr>
	<tr>
		<td>six</td>
		<td>six-1.15.0-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>snapdragon</td>
		<td>snapdragon-0.8.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>snapdragon-node</td>
		<td>snapdragon-node-2.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>snapdragon-util</td>
		<td>snapdragon-util-3.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>soupsieve</td>
		<td>soupsieve-1.9.6-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@types/source-list-map</td>
		<td>source-list-map-0.1.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>source-map</td>
		<td>source-map-0.5.7.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>source-map</td>
		<td>source-map-0.6.1.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>source-map</td>
		<td>source-map-0.7.3.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>source-map-resolve</td>
		<td>source-map-resolve-0.5.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>source-map-support</td>
		<td>source-map-support-0.5.19.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>source-map-url</td>
		<td>source-map-url-0.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>split-string</td>
		<td>split-string-3.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>sprintf</td>
		<td>sprintf-1.0.3.js</td>
		<td>BSD</td>
	</tr>
	<tr>
		<td>sprintf-js</td>
		<td>sprintf-js-1.0.3.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>static-extend</td>
		<td>static-extend-0.1.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>string.prototype.trimend</td>
		<td>string.prototype.trimend-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>string.prototype.trimleft</td>
		<td>string.prototype.trimleft-2.1.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>string.prototype.trimright</td>
		<td>string.prototype.trimright-2.1.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>string.prototype.trimstart</td>
		<td>string.prototype.trimstart-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>string_decoder</td>
		<td>string_decoder-1.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>strip-ansi</td>
		<td>strip-ansi-3.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>strongly-connected-components</td>
		<td>strongly-connected-components-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>supports-color</td>
		<td>supports-color-5.5.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>swagger-ui</td>
		<td>swagger-ui-bundle-3.37.0.js</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>swagger-ui</td>
		<td>swagger-ui-standalone-preset-3.37.0.js</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>symbol-observable</td>
		<td>symbol-observable-1.2.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@types/tapable</td>
		<td>tapable-1.0.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>tapable</td>
		<td>tapable-1.1.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>Jstarfish</td>
		<td>Technical-Learning-609d9d75ca68e30aee8757b26f52bf132c644be7</td>
		<td>ISC</td>
	</tr>
	<tr>
		<td>termcolor</td>
		<td>termcolor-1.1.0.tar.gz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>terser</td>
		<td>terser-4.7.0.tgz</td>
		<td>BSD 2</td>
	</tr>
	<tr>
		<td>tiny-invariant</td>
		<td>tiny-invariant-1.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>tiny-invariant</td>
		<td>tiny-invariant-1.0.6.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>tiny-warning</td>
		<td>tiny-warning-1.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>tiny-warning</td>
		<td>tiny-warning-1.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>tippy.js</td>
		<td>tippy-bundle.iife-5.2.1.min.js</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>tippy.js</td>
		<td>tippy.js-6.2.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>to-object-path</td>
		<td>to-object-path-0.3.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>to-regex</td>
		<td>to-regex-3.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>to-regex-range</td>
		<td>to-regex-range-2.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>tslib</td>
		<td>tslib-1.10.0.js</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>tslib</td>
		<td>tslib-1.10.0.tgz</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>tslib</td>
		<td>tslib-1.13.0.js</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>tslib</td>
		<td>tslib.es6-1.10.0.js</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>tslib</td>
		<td>tslib.es6-1.13.0.js</td>
		<td>Apache 2.0</td>
	</tr>
	<tr>
		<td>typescript-fsa</td>
		<td>typescript-fsa-2.5.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>typescript-fsa-reducers</td>
		<td>typescript-fsa-reducers-0.4.5.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>ua-parser-js</td>
		<td>ua-parser-js-0.7.18.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@types/uglify-js</td>
		<td>uglify-js-3.9.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>uncontrollable</td>
		<td>uncontrollable-4.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>union-value</td>
		<td>union-value-1.0.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>unset-value</td>
		<td>unset-value-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>urix</td>
		<td>urix-0.1.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>urllib3</td>
		<td>urllib3-1.24.3-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>urllib3</td>
		<td>urllib3-1.26.3-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>use</td>
		<td>use-3.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>util-deprecate</td>
		<td>util-deprecate-1.0.2.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>util.promisify</td>
		<td>util.promisify-1.0.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>utila</td>
		<td>utila-0.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>uuid</td>
		<td>uuid-7.0.3.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>validator</td>
		<td>validator-10.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>value-equal</td>
		<td>value-equal-0.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>warning</td>
		<td>warning-3.0.0.tgz</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>wcwidth</td>
		<td>wcwidth-0.2.5-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@types/webpack</td>
		<td>webpack-4.41.17.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>@types/webpack-sources</td>
		<td>webpack-sources-1.4.0.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>websocket_client</td>
		<td>websocket_client-0.57.0-py2.py3-none-any.whl</td>
		<td>BSD 3</td>
	</tr>
	<tr>
		<td>whatwg-fetch</td>
		<td>whatwg-fetch-2.0.4.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>worker-rpc</td>
		<td>worker-rpc-0.1.1.tgz</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>zipp</td>
		<td>zipp-1.2.0-py2.py3-none-any.whl</td>
		<td>MIT</td>
	</tr>
	<tr>
		<td>github.com/projectcalico/bird</td>
		<td>github.com/projectcalico/bird/blob/v0.3.3</td>
		<td>GPL</td>
	</tr>
	<tr>
		<td>egress-gateway</td>
		<td>egress-gateway</td>
		<td>Tigera Proprietory</td>
	</tr>
</tbody>
</table>
