# Forklift controller, plain Kubernetes.
#
# Apply after forklift-operator-kubernetes.yaml. The operator expands this into the
# full set of Forklift deployments.
---
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: konveyor-forklift
spec:
  k8s_cluster: 'true'
  feature_ui_plugin: 'false'
  feature_cli_download: 'false'
  feature_ocp_live_migration: 'false'
  feature_validation: 'true'
  feature_volume_populator: 'true'
