#!/usr/bin/env bash

# This script performs a regex operation on the autogenerated API docs.
# The generated docs are valid HTML, but not valid JSX, which breaks the
# build in Docusaurus 3.
#

# This script was built to be called in the Makefile's build-operator-reference target.

file=$1

# Moves all <p> and </p> tags to their own line.
perl -0777 -pi -e 's/(<p[^>]*>)([\s\S]*?)(<\/p>)/$1\n$2\n$3/g' ${file}
# Moves all <h2> </h2> tag to the same line.
perl -0777 -pi -e 's/(<h2[^>]*)/$1 class="anchor anchorWithStickyNavbar"/g' ${file}
# Moves all <h3> </h3> tag to the same line.
perl -0777 -pi -e 's/(<h3[^>]*)/$1 class="anchor anchorWithStickyNavbar"/g' ${file}
# Moves all <h3> </h3> tag to the same line.
perl -0777 -pi -e 's/(<h3[^>]*>)([\s\S]*?)\n(<\/h3>)/$1$2$3/g' ${file}
# Moves all <td> </td> tags to their own line.
perl -0777 -pi -e 's/(<td>)([\s\S]*?)(<\/td>)/$1\n$2\n$3/g' ${file}

exit