---
extends: substitution
message: "Use '%s' instead of '%s'."
level: error
ignorecase: true
swap:
  'dataplane': 'data plane'
  'dataplanes': 'data planes'
  'ebpf': 'eBPF'
  'helm': 'Helm'
  'kubernetes': 'Kubernetes'
  'minikube': 'minikube'
  'quick start': 'quickstart'
  'addon': 'add-on'

