---
extends: substitution
message: "Use '%s' instead of '%s'."
level: error
ignorecase: true
swap:
  'addon': 'add-on'
  'dataplane': 'data plane'
  'dataplanes': 'data planes'
  'ebpf': 'eBPF'
  'fortigate': 'FortiGate'
  'helm': 'Helm'
  'http': 'HTTP'
  'icmp': 'ICMP'
  'ipam': 'IPAM'
  'kubernetes': 'Kubernetes'
  'minikube': 'minikube'
  'mtu': 'MTU'
  'quick start': 'quickstart'
  'sctp': 'SCTP'
  'tcp': 'TCP'
  'udp': 'UDP'
  'vxlan': 'VXLAN'

