name: reviewdog
on: [pull_request]
jobs:
  vale:
    name: Validate React code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node.js with Yarn
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run unit tests
        run: yarn test:components:ci
